BEGIN TRANSACTION;
DROP TABLE IF EXISTS key;
CREATE TABLE key (sharps INTEGER, major INTEGER, name TEXT);
INSERT INTO key VALUES (0,0,'C major');
INSERT INTO key VALUES (0,1,'A minor');
INSERT INTO key VALUES (1,0,'G major');
INSERT INTO key VALUES (1,1,'E minor');
INSERT INTO key VALUES (2,0,'D major');
INSERT INTO key VALUES (2,1,'B minor');
INSERT INTO key VALUES (3,0,'A major');
INSERT INTO key VALUES (3,1,'F# minor');
INSERT INTO key VALUES (4,0,'E major');
INSERT INTO key VALUES (4,1,'C# minor');
INSERT INTO key VALUES (5,0,'B major');
INSERT INTO key VALUES (5,1,'G# minor');
INSERT INTO key VALUES (6,0,'F# major');
INSERT INTO key VALUES (6,1,'D# minor');
INSERT INTO key VALUES (7,0,'C# major');
INSERT INTO key VALUES (7,1,'A# minor');
INSERT INTO key VALUES (-1,0,'F major');
INSERT INTO key VALUES (-1,1,'D minor');
INSERT INTO key VALUES (-2,0,'Bb major');
INSERT INTO key VALUES (-2,1,'G minor');
INSERT INTO key VALUES (-3,0,'Eb major');
INSERT INTO key VALUES (-3,1,'C minor');
INSERT INTO key VALUES (-4,0,'Ab major');
INSERT INTO key VALUES (-4,1,'F minor');
INSERT INTO key VALUES (-5,0,'Db major');
INSERT INTO key VALUES (-5,1,'Bb minor');
INSERT INTO key VALUES (-6,0,'Gb major');
INSERT INTO key VALUES (-6,1,'Eb minor');
INSERT INTO key VALUES (-7,0,'Cb major');
INSERT INTO key VALUES (-7,1,'Ab minor');
DROP TABLE IF EXISTS instruments;
CREATE TABLE instruments (id INTEGER, family TEXT, name TEXT);
INSERT INTO instruments VALUES (1,'Piano','Acoustic Grand Piano');
INSERT INTO instruments VALUES (2,'Piano','Bright Acoustic Piano');
INSERT INTO instruments VALUES (3,'Piano','Electric Grand Piano');
INSERT INTO instruments VALUES (4,'Piano','Honky-tonk Piano');
INSERT INTO instruments VALUES (5,'Piano','Electric Piano 1');
INSERT INTO instruments VALUES (6,'Piano','Electric Piano 2');
INSERT INTO instruments VALUES (7,'Piano','Harpsichord');
INSERT INTO instruments VALUES (8,'Piano','Clavichord');
INSERT INTO instruments VALUES (9,'Chromatic Percussion','Celesta');
INSERT INTO instruments VALUES (10,'Chromatic Percussion','Glockenspiel');
INSERT INTO instruments VALUES (11,'Chromatic Percussion','Music Box');
INSERT INTO instruments VALUES (12,'Chromatic Percussion','Vibraphone');
INSERT INTO instruments VALUES (13,'Chromatic Percussion','Marimba');
INSERT INTO instruments VALUES (14,'Chromatic Percussion','Xylophone');
INSERT INTO instruments VALUES (15,'Chromatic Percussion','Tubular Bells');
INSERT INTO instruments VALUES (16,'Chromatic Percussion','Dulcimer');
INSERT INTO instruments VALUES (17,'Organ','Drawbar Organ');
INSERT INTO instruments VALUES (18,'Organ','Percussive Organ');
INSERT INTO instruments VALUES (19,'Organ','Rock Organ');
INSERT INTO instruments VALUES (20,'Organ','Church Organ');
INSERT INTO instruments VALUES (21,'Organ','Reed Organ');
INSERT INTO instruments VALUES (22,'Organ','Accordion Organ');
INSERT INTO instruments VALUES (23,'Organ','Harmonica');
INSERT INTO instruments VALUES (24,'Organ','Tango Organ');
INSERT INTO instruments VALUES (25,'Guitar','Nylon Guitar');
INSERT INTO instruments VALUES (26,'Guitar','Steel Guitar');
INSERT INTO instruments VALUES (27,'Guitar','Jazz Guitar');
INSERT INTO instruments VALUES (28,'Guitar','Clean Guitar');
INSERT INTO instruments VALUES (29,'Guitar','Muted Guitar');
INSERT INTO instruments VALUES (30,'Guitar','Overdrive Guitar');
INSERT INTO instruments VALUES (31,'Guitar','Distorted Guitar');
INSERT INTO instruments VALUES (32,'Guitar','Harmonic Guitar');
INSERT INTO instruments VALUES (33,'Bass','Acoustic Bass');
INSERT INTO instruments VALUES (34,'Bass','Fingered Bass');
INSERT INTO instruments VALUES (35,'Bass','Pick Bass');
INSERT INTO instruments VALUES (36,'Bass','Fretless Bass');
INSERT INTO instruments VALUES (37,'Bass','Slap Bass 1');
INSERT INTO instruments VALUES (38,'Bass','Slap Bass 2');
INSERT INTO instruments VALUES (39,'Bass','Synth Bass 1');
INSERT INTO instruments VALUES (40,'Bass','Synth Bass 2');
INSERT INTO instruments VALUES (41,'Strings','Violin');
INSERT INTO instruments VALUES (42,'Strings','Viola');
INSERT INTO instruments VALUES (43,'Strings','Cello');
INSERT INTO instruments VALUES (44,'Strings','Double Bass');
INSERT INTO instruments VALUES (45,'Strings','Tremolo Strings');
INSERT INTO instruments VALUES (46,'Strings','Pizzicato Strings');
INSERT INTO instruments VALUES (47,'Strings','Harp');
INSERT INTO instruments VALUES (48,'Strings','Timpani');
INSERT INTO instruments VALUES (49,'Ensemble','String Ensemble 1');
INSERT INTO instruments VALUES (50,'Ensemble','String Ensemble 2');
INSERT INTO instruments VALUES (51,'Ensemble','SynthStrings 1');
INSERT INTO instruments VALUES (52,'Ensemble','SynthStrings 2');
INSERT INTO instruments VALUES (53,'Ensemble','Choir Aahs');
INSERT INTO instruments VALUES (54,'Ensemble','Voice Oohs');
INSERT INTO instruments VALUES (55,'Ensemble','Synth Voice');
INSERT INTO instruments VALUES (56,'Ensemble','Orchestra Hit');
INSERT INTO instruments VALUES (57,'Brass','Trumpet');
INSERT INTO instruments VALUES (58,'Brass','Trombone');
INSERT INTO instruments VALUES (59,'Brass','Tuba');
INSERT INTO instruments VALUES (60,'Brass','Muted Trumpet');
INSERT INTO instruments VALUES (61,'Brass','French Horn');
INSERT INTO instruments VALUES (62,'Brass','Brass Section');
INSERT INTO instruments VALUES (63,'Brass','SynthBrass 1');
INSERT INTO instruments VALUES (64,'Brass','SynthBrass 2');
INSERT INTO instruments VALUES (65,'Reed','Soprano Sax');
INSERT INTO instruments VALUES (66,'Reed','Alto Sax');
INSERT INTO instruments VALUES (67,'Reed','Tenor Sax');
INSERT INTO instruments VALUES (68,'Reed','Baritone Sax');
INSERT INTO instruments VALUES (69,'Reed','Oboe');
INSERT INTO instruments VALUES (70,'Reed','English Horn');
INSERT INTO instruments VALUES (71,'Reed','Bassoon');
INSERT INTO instruments VALUES (72,'Reed','Clarinet');
INSERT INTO instruments VALUES (73,'Pipe','Piccolo');
INSERT INTO instruments VALUES (74,'Pipe','Flute');
INSERT INTO instruments VALUES (75,'Pipe','Recorder');
INSERT INTO instruments VALUES (76,'Pipe','Pan Flute');
INSERT INTO instruments VALUES (77,'Pipe','Blow Bottle');
INSERT INTO instruments VALUES (78,'Pipe','Shakuhachi');
INSERT INTO instruments VALUES (79,'Pipe','Whistle');
INSERT INTO instruments VALUES (80,'Pipe','Ocarina');
INSERT INTO instruments VALUES (81,'Synth Lead','Square Lead');
INSERT INTO instruments VALUES (82,'Synth Lead','Sawtooth Lead');
INSERT INTO instruments VALUES (83,'Synth Lead','Calliope Lead');
INSERT INTO instruments VALUES (84,'Synth Lead','Chiff Lead');
INSERT INTO instruments VALUES (85,'Synth Lead','Charang Lead');
INSERT INTO instruments VALUES (86,'Synth Lead','Voice Lead');
INSERT INTO instruments VALUES (87,'Synth Lead','Fifths Lead');
INSERT INTO instruments VALUES (88,'Synth Lead','Bass Lead');
INSERT INTO instruments VALUES (89,'Synth Pad','New Age Pad');
INSERT INTO instruments VALUES (90,'Synth Pad','Warm Pad');
INSERT INTO instruments VALUES (91,'Synth Pad','Polysynth Pad');
INSERT INTO instruments VALUES (92,'Synth Pad','Choir Pad');
INSERT INTO instruments VALUES (93,'Synth Pad','Bowed Pad');
INSERT INTO instruments VALUES (94,'Synth Pad','Metallic Pad');
INSERT INTO instruments VALUES (95,'Synth Pad','Halo Pad');
INSERT INTO instruments VALUES (96,'Synth Pad','Sweep Pad');
INSERT INTO instruments VALUES (97,'Synth Effects','Rain FX');
INSERT INTO instruments VALUES (98,'Synth Effects','Sountrack FX');
INSERT INTO instruments VALUES (99,'Synth Effects','Crystal FX');
INSERT INTO instruments VALUES (100,'Synth Effects','Atmosphere FX');
INSERT INTO instruments VALUES (101,'Synth Effects','Brightness FX');
INSERT INTO instruments VALUES (102,'Synth Effects','Goblins FX');
INSERT INTO instruments VALUES (103,'Synth Effects','Echoes FX');
INSERT INTO instruments VALUES (104,'Synth Effects','Sci-fi FX');
INSERT INTO instruments VALUES (105,'Ethnic','Sitar');
INSERT INTO instruments VALUES (106,'Ethnic','Banjo');
INSERT INTO instruments VALUES (107,'Ethnic','Shamisen');
INSERT INTO instruments VALUES (108,'Ethnic','Koto');
INSERT INTO instruments VALUES (109,'Ethnic','Kalimba');
INSERT INTO instruments VALUES (110,'Ethnic','Bag Pipe');
INSERT INTO instruments VALUES (111,'Ethnic','Fiddle');
INSERT INTO instruments VALUES (112,'Ethnic','Shanai');
INSERT INTO instruments VALUES (113,'Percussive','Tinkle Bell');
INSERT INTO instruments VALUES (114,'Percussive','Agogo');
INSERT INTO instruments VALUES (115,'Percussive','Steel Drums');
INSERT INTO instruments VALUES (116,'Percussive','Woodblock');
INSERT INTO instruments VALUES (117,'Percussive','Taiko Drums');
INSERT INTO instruments VALUES (118,'Percussive','Melodic Tom');
INSERT INTO instruments VALUES (119,'Percussive','Synth Drums');
INSERT INTO instruments VALUES (120,'Percussive','Reverse Cymbal');
INSERT INTO instruments VALUES (121,'Sound Effects','Guitar Fret Noise');
INSERT INTO instruments VALUES (122,'Sound Effects','Breath Noise');
INSERT INTO instruments VALUES (123,'Sound Effects','Seashore');
INSERT INTO instruments VALUES (124,'Sound Effects','Bird Tweet');
INSERT INTO instruments VALUES (125,'Sound Effects','Telephone Ring');
INSERT INTO instruments VALUES (126,'Sound Effects','Helicopter');
INSERT INTO instruments VALUES (127,'Sound Effects','Applause');
INSERT INTO instruments VALUES (128,'Sound Effects','Gunshot');
END TRANSACTION;
